// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/corporations": {
            "get": {
                "description": "Get the list of corporations available for selection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "corporations"
                ],
                "summary": "Get available corporations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Corporation"
                            }
                        }
                    }
                }
            }
        },
        "/games/{id}": {
            "get": {
                "description": "Retrieve a game state by its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "games"
                ],
                "summary": "Get game by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.GameState"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the server is running",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Award": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "fundedBy": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Corporation": {
            "type": "object",
            "properties": {
                "ability": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "logoPath": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "startingCards": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "startingMegaCredits": {
                    "type": "integer"
                },
                "startingProduction": {
                    "$ref": "#/definitions/domain.ResourcesMap"
                },
                "startingResources": {
                    "$ref": "#/definitions/domain.ResourcesMap"
                },
                "startingTR": {
                    "type": "integer"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Tag"
                    }
                }
            }
        },
        "domain.DraftDirection": {
            "type": "string",
            "enum": [
                "clockwise",
                "counter_clockwise"
            ],
            "x-enum-varnames": [
                "DraftDirectionClockwise",
                "DraftDirectionCounterClockwise"
            ]
        },
        "domain.GameExpansion": {
            "type": "string",
            "enum": [
                "prelude",
                "venus",
                "colonies",
                "turmoil",
                "big_box",
                "ares",
                "moon",
                "pathfinders",
                "prelude2",
                "ceo",
                "promo",
                "community",
                "underworld",
                "escape_velocity",
                "star_wars"
            ],
            "x-enum-varnames": [
                "GameExpansionPrelude",
                "GameExpansionVenus",
                "GameExpansionColonies",
                "GameExpansionTurmoil",
                "GameExpansionBigBox",
                "GameExpansionAres",
                "GameExpansionMoon",
                "GameExpansionPathfinders",
                "GameExpansionPrelude2",
                "GameExpansionCEO",
                "GameExpansionPromo",
                "GameExpansionCommunity",
                "GameExpansionUnderworld",
                "GameExpansionEscapeVelocity",
                "GameExpansionStarWars"
            ]
        },
        "domain.GamePhase": {
            "type": "string",
            "enum": [
                "setup",
                "corporation_selection",
                "initial_research",
                "prelude",
                "research",
                "action",
                "production",
                "draft",
                "game_end"
            ],
            "x-enum-varnames": [
                "GamePhaseSetup",
                "GamePhaseCorporationSelection",
                "GamePhaseInitialResearch",
                "GamePhasePrelude",
                "GamePhaseResearch",
                "GamePhaseAction",
                "GamePhaseProduction",
                "GamePhaseDraft",
                "GamePhaseGameEnd"
            ]
        },
        "domain.GameSettings": {
            "type": "object",
            "properties": {
                "altVenusBoard": {
                    "type": "boolean"
                },
                "bannedCards": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "breakthrough": {
                    "type": "boolean"
                },
                "coloniesExtension": {
                    "type": "boolean"
                },
                "corporateEra": {
                    "type": "boolean"
                },
                "customCorporationsList": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "draftVariant": {
                    "type": "boolean"
                },
                "escapeVelocityExpansion": {
                    "type": "boolean"
                },
                "escapeVelocityMode": {
                    "type": "boolean"
                },
                "escapeVelocityPenalty": {
                    "type": "integer"
                },
                "escapeVelocityPeriod": {
                    "type": "integer"
                },
                "escapeVelocityThreshold": {
                    "type": "integer"
                },
                "expansions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.GameExpansion"
                    }
                },
                "fast": {
                    "type": "boolean"
                },
                "heatFor": {
                    "type": "boolean"
                },
                "includeVenusMA": {
                    "type": "boolean"
                },
                "includedCards": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "initialDraft": {
                    "type": "boolean"
                },
                "moonExpansion": {
                    "type": "boolean"
                },
                "moonStandardProjectVariant": {
                    "type": "boolean"
                },
                "pathfindersExpansion": {
                    "type": "boolean"
                },
                "preludeExtension": {
                    "type": "boolean"
                },
                "randomFirstPlayer": {
                    "type": "boolean"
                },
                "removeNegativeAttackCards": {
                    "type": "boolean"
                },
                "requiresMoonTrackCompletion": {
                    "type": "boolean"
                },
                "requiresVenusTrackCompletion": {
                    "type": "boolean"
                },
                "showOtherPlayersVP": {
                    "type": "boolean"
                },
                "soloTR": {
                    "type": "boolean"
                },
                "turmoilExtension": {
                    "type": "boolean"
                },
                "twoTempTerraformingThreshold": {
                    "type": "boolean"
                },
                "underworldExpansion": {
                    "type": "boolean"
                },
                "venusNextExtension": {
                    "type": "boolean"
                }
            }
        },
        "domain.GameState": {
            "type": "object",
            "properties": {
                "awards": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Award"
                    }
                },
                "corporationDraft": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "currentActionCount": {
                    "type": "integer"
                },
                "currentPlayer": {
                    "type": "string"
                },
                "deck": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "discardPile": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "draftDirection": {
                    "$ref": "#/definitions/domain.DraftDirection"
                },
                "firstPlayer": {
                    "type": "string"
                },
                "gameSettings": {
                    "$ref": "#/definitions/domain.GameSettings"
                },
                "generation": {
                    "type": "integer"
                },
                "globalParameters": {
                    "$ref": "#/definitions/domain.GlobalParameters"
                },
                "id": {
                    "type": "string"
                },
                "maxActionsPerTurn": {
                    "type": "integer"
                },
                "milestones": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Milestone"
                    }
                },
                "phase": {
                    "$ref": "#/definitions/domain.GamePhase"
                },
                "players": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Player"
                    }
                },
                "soloMode": {
                    "type": "boolean"
                },
                "turn": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "domain.GlobalParameters": {
            "type": "object",
            "properties": {
                "oceans": {
                    "description": "0 to 9",
                    "type": "integer"
                },
                "oxygen": {
                    "description": "0 to 14%",
                    "type": "integer"
                },
                "temperature": {
                    "description": "-30 to +8 (in steps of 2)",
                    "type": "integer"
                }
            }
        },
        "domain.HexCoordinate": {
            "type": "object",
            "properties": {
                "q": {
                    "description": "Column",
                    "type": "integer"
                },
                "r": {
                    "description": "Row",
                    "type": "integer"
                },
                "s": {
                    "description": "Diagonal (q + r + s = 0)",
                    "type": "integer"
                }
            }
        },
        "domain.Milestone": {
            "type": "object",
            "properties": {
                "claimedBy": {
                    "type": "string"
                },
                "cost": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Player": {
            "type": "object",
            "properties": {
                "actionsRemaining": {
                    "type": "integer"
                },
                "actionsTaken": {
                    "type": "integer"
                },
                "availableActions": {
                    "type": "integer"
                },
                "corporation": {
                    "type": "string"
                },
                "hand": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "passed": {
                    "type": "boolean"
                },
                "playedCards": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "production": {
                    "$ref": "#/definitions/domain.ResourcesMap"
                },
                "reserved": {
                    "$ref": "#/definitions/domain.ResourcesMap"
                },
                "resources": {
                    "$ref": "#/definitions/domain.ResourcesMap"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.Tag"
                    }
                },
                "terraformRating": {
                    "type": "integer"
                },
                "tilePositions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.HexCoordinate"
                    }
                },
                "victoryPoints": {
                    "type": "integer"
                }
            }
        },
        "domain.ResourcesMap": {
            "type": "object",
            "properties": {
                "credits": {
                    "type": "integer"
                },
                "energy": {
                    "type": "integer"
                },
                "heat": {
                    "type": "integer"
                },
                "plants": {
                    "type": "integer"
                },
                "steel": {
                    "type": "integer"
                },
                "titanium": {
                    "type": "integer"
                }
            }
        },
        "domain.Tag": {
            "type": "string",
            "enum": [
                "building",
                "space",
                "power",
                "science",
                "microbe",
                "animal",
                "plant",
                "earth",
                "jovian",
                "city",
                "event",
                "wild",
                "venus",
                "moon",
                "mars",
                "clone"
            ],
            "x-enum-varnames": [
                "TagBuilding",
                "TagSpace",
                "TagPower",
                "TagScience",
                "TagMicrobe",
                "TagAnimal",
                "TagPlant",
                "TagEarth",
                "TagJovian",
                "TagCity",
                "TagEvent",
                "TagWild",
                "TagVenus",
                "TagMoon",
                "TagMars",
                "TagClone"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Terraforming Mars API",
	Description:      "Digital implementation of Terraforming Mars board game backend API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
