// THIS FILE IS AUTO-GENERATED BY TYGO
// DO NOT EDIT MANUALLY
// Run 'make generate-types' or 'tygo generate' from the backend directory to regenerate

// Resource types
export type ResourceType =
  | "credits"
  | "steel"
  | "titanium"
  | "plants"
  | "energy"
  | "heat";

export type GlobalParameter = "temperature" | "oxygen" | "oceans";

export interface PlayerResources {
  credits: number;
  steel: number;
  titanium: number;
  plants: number;
  energy: number;
  heat: number;
}

export interface PlayerProduction {
  credits: number;
  steel: number;
  titanium: number;
  plants: number;
  energy: number;
  heat: number;
}

export interface GlobalParameters {
  temperature: number; // -30 to +8
  oxygen: number; // 0 to 14
  oceans: number; // 0 to 9
}

export interface ResourceCost {
  credits?: number;
  steel?: number;
  titanium?: number;
  plants?: number;
  energy?: number;
  heat?: number;
}

export interface ResourceGain {
  credits?: number;
  steel?: number;
  titanium?: number;
  plants?: number;
  energy?: number;
  heat?: number;
}

export interface ProductionChange {
  credits?: number;
  steel?: number;
  titanium?: number;
  plants?: number;
  energy?: number;
  heat?: number;
}

// Card types
export type CardType =
  | "automated"
  | "active"
  | "event"
  | "corporation"
  | "prelude";

export type CardTag =
  | "building"
  | "space"
  | "power"
  | "science"
  | "microbe"
  | "animal"
  | "plant"
  | "earth"
  | "jovian"
  | "city"
  | "venus"
  | "mars"
  | "moon"
  | "wild"
  | "event"
  | "clone";

export interface CardRequirement {
  type: string;
  value?: any;
  min?: number;
  max?: number;
  isGlobal?: boolean;
  description?: string;
}

export interface CardDefinition {
  id: string;
  name: string;
  cost: number;
  type: CardType;
  tags: CardTag[];
  victoryPoints?: number;
  requirements?: CardRequirement[];
  effects: any[];
  description: string;
  flavor?: string;
  expansion?: string;
  renderData?: RenderData;
}

export interface Card {
  id: string;
  definition?: CardDefinition;
  resources?: number;
  playedBy?: string;
  isUsed?: boolean;
}

export interface RenderData {
  cost?: number;
  description?: string;
  effects?: RenderEffect[];
}

export interface RenderEffect {
  type: string;
  amount?: number;
  asterix?: boolean;
}

// Player types
export interface Player {
  id: string;
  name: string;
  resources: PlayerResources;
  production: PlayerProduction;
  terraformRating: number;
  victoryPoints: number;
  corporation?: string;
  passed?: boolean;
  playedCards: Card[];
  hand: Card[];
  availableActions: number;
  tags: CardTag[];
  actionsTaken?: number;
  actionsRemaining?: number;
}

export type PlayerPhase =
  | "waiting"
  | "drafting"
  | "research"
  | "action"
  | "production"
  | "passed";

export interface PlayerAction {
  type: PlayerActionType;
  playerId: string;
  data?: any;
}

export type PlayerActionType =
  | "play_card"
  | "standard_project"
  | "pass"
  | "claim_milestone"
  | "fund_award"
  | "use_effect"
  | "place_tile"
  | "raise_parameter";

// Game types
export interface GameState {
  id: string;
  players: Player[];
  currentPlayer: string;
  generation: number;
  phase: GamePhase;
  globalParameters: GlobalParameters;
  milestones: Milestone[];
  awards: Award[];
  firstPlayer: string;
  corporationDraft?: boolean;
  deck: string[];
  discardPile: string[];
  soloMode: boolean;
  turn: number;
  draftDirection?: DraftDirection;
  gameSettings: GameSettings;
  currentActionCount?: number;
  maxActionsPerTurn?: number;
}

export type GamePhase =
  | "setup"
  | "corporation_selection"
  | "initial_research"
  | "prelude"
  | "research"
  | "action"
  | "production"
  | "draft"
  | "game_end";

export type DraftDirection = "clockwise" | "counter_clockwise";

export interface GameSettings {
  expansions: GameExpansion[];
  corporateEra: boolean;
  draftVariant: boolean;
  initialDraft: boolean;
  preludeExtension: boolean;
  venusNextExtension: boolean;
  coloniesExtension: boolean;
  turmoilExtension: boolean;
  removeNegativeAttackCards: boolean;
  includeVenusMA: boolean;
  moonExpansion: boolean;
  pathfindersExpansion: boolean;
  underworldExpansion: boolean;
  escapeVelocityExpansion: boolean;
  fast: boolean;
  showOtherPlayersVP: boolean;
  customCorporationsList?: string[];
  bannedCards?: string[];
  includedCards?: string[];
  soloTR: boolean;
  randomFirstPlayer: boolean;
  requiresVenusTrackCompletion: boolean;
  requiresMoonTrackCompletion: boolean;
  moonStandardProjectVariant: boolean;
  altVenusBoard: boolean;
  escapeVelocityMode: boolean;
  escapeVelocityThreshold: number;
  escapeVelocityPeriod: number;
  escapeVelocityPenalty: number;
  twoTempTerraformingThreshold: boolean;
  heatFor: boolean;
  breakthrough: boolean;
}

export type GameExpansion =
  | "prelude"
  | "venus"
  | "colonies"
  | "turmoil"
  | "big_box"
  | "ares"
  | "moon"
  | "pathfinders"
  | "prelude2"
  | "ceo"
  | "promo"
  | "community"
  | "underworld"
  | "escape_velocity"
  | "star_wars";

export interface GameEvent {
  id: string;
  type: GameEventType;
  triggeredBy?: string;
  data?: any;
  timestamp: number;
}

export type GameEventType =
  | "game_started"
  | "player_joined"
  | "player_left"
  | "card_played"
  | "tile_placed"
  | "parameter_increased"
  | "milestone_claimed"
  | "award_funded"
  | "generation_end"
  | "game_end"
  | "production_phase"
  | "research_phase";

export interface StandardProject {
  id: string;
  name: string;
  cost: number;
  description: string;
}

export type StandardProjectType =
  | "sell_patents"
  | "power_plant"
  | "asteroid"
  | "aquifer"
  | "greenery"
  | "city"
  | "air_scrapping"
  | "buffer_gas";

// Milestone types
export interface Milestone {
  id: string;
  name: string;
  description: string;
  claimedBy?: string;
  cost: number;
}

export type MilestoneType =
  | "terraformer"
  | "mayor"
  | "gardener"
  | "builder"
  | "planner";

// Award types
export interface Award {
  id: string;
  name: string;
  description: string;
  fundedBy?: string;
  cost: number;
}

export type AwardType =
  | "landlord"
  | "banker"
  | "scientist"
  | "thermalist"
  | "miner";
